# Generated by Django 4.0.6 on 2023-07-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('rating', models.CharField(max_length=10)),
                ('year_release', models.IntegerField()),
                ('metacritic_rating', models.IntegerField()),
                ('runtime', models.CharField(max_length=10)),
                ('genres', models.ManyToManyField(to='list_movies.genre')),
            ],
        ),
    ]
